---
version: '3'
services:
  minute_agg:
    image: minute_agg
    container_name: minute_agg
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 9092
    networks: 
      - broker-kafka

networks: 
  broker-kafka:
    driver: bridge  