---
version: '3'
services:
  producer:
    image: producer
    container_name: python_producer
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 9092
    networks: 
      - broker-kafka

networks: 
  broker-kafka:
    driver: bridge  